name: Sync comments to Development ticket

on:
  issue_comment:
    {}

jobs:
  sync-issue-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue id of confirmed issue (when the issue_confirmed label is added)
        id: target_issue
        run: |
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Get Issue Fields on context
        id: get_issue_fields_on_context
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.WATCHER_ISSUE_SYNC }}
          script: |
            return await github.request(
              'GET /repos/{owner}/{repo}/issues/{issue_number}/issue-field-values', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: process.env.ISSUE_NUMBER,
                headers: {
                  'X-GitHub-Api-Version': '2026-03-10'
                }
              }
            );

      - name: Get all Octopodi Technologies Organization Issue Fields
        id: get_all_issue_fields_for_org
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.WATCHER_ISSUE_SYNC }}
          script: |
            const orgIssueFields = await octokit.request('GET /orgs/{org}/issue-fields', {
              org: 'octopodi-technologies',
              headers: {
                'X-GitHub-Api-Version': '2026-03-10'
              }
            });
            if (orgIssueFields.length === 0) {
              throw new Error("No organization Issue Fields are found.");
            }
            return orgIssueFields;

      - name: Get Octopodi Issue number from issue field
        uses: actions/github-script@v7
        id: get_octopodi_issue_number
        with:
          github-token: ${{ secrets.WATCHER_ISSUE_SYNC }}
          script: |
            const issueFields = ${{ steps.get_issue_fields_on_context.outputs.result }}
            const orgIssueFields = ${{ steps.get_all_issue_fields_for_org.outputs.result }}
            const linkageIdIssueField = orgIssueFields.data.filter(field => field.name === "Linkage Id");
            const linkageIssueFieldOnContext = issueFields.data.filter(field => field.id === linkageIdIssueField.id)[0];
            if (!linkageIssueFieldOnContext) {
              throw new Error("Linkage Id is not a set field on the issue.");
            }
            if (!linkageIssueFieldOnContext.value) {
              throw new Error("Linkage Id does not have a value on the issue.");
            }
            return linkageIssueFieldOnContext.value;

      - name: Update Octopodi Issue
        uses: actions/github-script@v7
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        with:
          github-token: ${{ secrets.WATCHER_ISSUE_SYNC }}
          script: |
            const githubContext = JSON.parse(process.env.GITHUB_CONTEXT);
            console.log(githubContext);
            const { action, comment } = githubContext;
            const { user } = comment;
            const body = [];
            switch (action) {
              case "created":
                body.push(`${user.login} has created a comment.`);
                body.push("```");
                body.push(comment.body);
                body.push("```");
                break;
              case "deleted":
                body.push(`${user.login} has deleted this comment:`);
                body.push("```");
                body.push(comment.body);
                body.push("```");
                break;
              case "edited":
                body.push(`${user.login} has edited a comment.`);
                body.push("from:");
                body.push("```");
                body.push(githubContext.changes.body.from);
                body.push("```");
                body.push("to:");
                body.push("```");
                body.push(comment.body)
                body.push("```");
                break;
              case "pinned":
                body.push(`${user.login} has pinned a comment.`);
                body.push("```");
                body.push(comment.body);
                body.push("```");
                break;
              case "unpinned":
                body.push(`${user.login} has unpinned a comment.`);
                body.push("```");
                body.push(comment.body);
                body.push("```");
                break;
            }
            const stringifiedBody = body.join("\n");
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: "octopodi",
              issue_number: ${{ steps.get_octopodi_issue_number.outputs.result }},
              body: stringifiedBody,
            });
